### ISSUE TITLE
(Custom Script Extension) Script failure causes following ARM template deployment to fail

### ISSUE THREAD

**Issue by jjjordanmsft** [Azure/azure-linux-extensions#89] opened 2016-01-19 22:13 UTC
When a script invoked by the Custom Script extension returns an error code, I've observed that the next ARM template deployment will also fail.  The real problem is that the *VM* is the resource that fails.  This poses a problem for custom scripts executed in ARM template deployments, because the custom script `dependsOn` the VM.  So, it will never run again and have a chance to correct itself.  (We use a `timestamp` in `settings` to ensure the script runs on each deployment).

Here's the error output from New-AzureRmResourceGroupDeployment:

```
VERBOSE: 12:41:22 AM - Create template deployment 'azuredeploy-####-####'.
VERBOSE: 12:41:30 AM - Resource Microsoft.Network/virtualNetworks '#####' provisioning status is succeeded
VERBOSE: 12:41:33 AM - Resource Microsoft.Storage/storageAccounts '#####' provisioning status is succeeded
VERBOSE: 12:41:33 AM - Resource Microsoft.Network/publicIPAddresses '#####' provisioning status is succeeded
VERBOSE: 12:41:36 AM - Resource Microsoft.Compute/virtualMachines '#####' provisioning status is running
VERBOSE: 12:41:36 AM - Resource Microsoft.Network/networkInterfaces '#####' provisioning status is succeeded
New-AzureRmResourceGroupDeployment : 12:42:12 AM - Resource Microsoft.Compute/virtualMachines '#####' failed with message 'The resource 
operation completed with terminal provisioning state 'Failed'.'
At C:\#####\scripts\Deploy.ps1:65 char:11
+ $deploy = New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $T ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand
 
New-AzureRmResourceGroupDeployment : 12:42:12 AM - VM has reported a failure when processing extension 'shexec'. Error message: "Script returned an 
error.
---stdout---
---errout---
(error output)
".
At C:\#####\scripts\Deploy.ps1:65 char:11
+ $deploy = New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $T ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand
```

We can work around this problem by invoking custom scripts outside of ARM templates, but it still means we need an extra deploy to fix the issue.  Alternatively, I think that we can invoke "/bin/true" after a failed ARM template deployment to get the extension back into a non-error state.  However, I can see this issue affecting others, and working around it in this manner is non-intuitive.

**Comment by bingosummer** [comment] 2016-01-20 03:02
@jjjordanmsft 
Thanks for your report.
Could you please provide the template you are using and the reproduce steps?
Thanks

**Comment by boumenot** [comment] 2016-05-25 19:27
I haven't seen a response since January, so I'm closing.  Please re-open as necessary.

**Closed by boumenot** 2016-05-25 19:27 UTC

**Comment by alexandreweiss** [comment] 2018-03-01 10:18
Hi team, i have the exactly same issue. I have sent you email and will post outcome here if necessary.

**Comment by boumenot** [comment] 2018-03-01 17:20
We like to work in the open.  Please publish your data to this thread.

**Comment by alexandreweiss** [comment] 2018-03-01 22:44
In fact, the component which is in a "Failed" state is the VMSS itself, even if only the extention returned a >0 error code. As in any script, it is expected to, sometimes, face issue. Of course, any error code should be handled but at some point, it must be reported as "non OK" to be able to solve the problem and activate again the extension to receive a 0 error code. It is possible that the extension could fail because of an external condition like repository holding artifacts is not available, thuse preventing the extension to download them.
To summarize, i'm waiting for the real error code but i want to be able to activate the extension again without having to unsinstall it which is not clean in a Release Management / Automation process.

Below are some output : 

**VSTS Agent output shows the VMSS is failed :**
2018-03-01T09:49:45.0939180Z ##[error]9:49:44 AM - Resource Microsoft.Compute/virtualMachineScaleSets 'dev-emea-vm-spp' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'InstallProxy'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\nnf)\nchanged: [127.0.0.1] =
      }
    ]
  }
}'

**Extension configuration :** 
{
      "name": "[concat(variables('virtualMachines_nameEnv'),'/InstallProxy')]",
      "type": "Microsoft.Compute/virtualMachineScaleSets/extensions",
     "condition": "[equals(parameters('proxyShortName'), 'spp')]",
      "apiVersion": "[variables('computeApiVersion')]",
      "location": "[resourceGroup().location]",
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachineScaleSets/', variables('virtualMachines_nameEnv'))]"
      ],
      "properties": {
        "publisher": "Microsoft.Azure.Extensions",
        "type": "CustomScript",
        "typeHandlerVersion": "2.0",
        "autoUpgradeMinorVersion": true,
        "settings": {
          "fileUris": "[variables('prxExtensionFilesUri')]"
        },
        "protectedSettings": {
          "commandToExecute": "[variables('commandToExecute')]"
        }
      }
    }

**Comment by boumenot** [comment] 2018-03-05 21:31
You're reporting an error for an extension not in this repository.  You want https://github.com/Azure/custom-script-extension-linux.

If you want to run the extension again, simply send down a new configuration.  If the configuration is **identical** to the previous configuration it will not be executed.  The (README for CustomScript)[https://github.com/Azure/custom-script-extension-linux#11-public-settings]
suggests you add a timestamp value to your configuration, and increment it for any re-execution.

**Comment by boumenot** [comment] 2018-03-12 17:21
If I run a script that exits with a non-zero code it fails immediately, but that's not what you're describing. I am not sure what's different about what you are doing vs. what I am doing. 

Command that will fail, and return non-zero exit status.  I tried to simulate a longer running script, by delaying the *bad* command for six minutes.

```json
{
    "commandToExecute": "sleep 360 && ls /does-not-exist"
}
```

The command failed in a little over six minutes, and I was able to issue another command.

Output:

```text
Deployment failed. Correlation ID: 681e769a-16b3-4315-9374-a8e29ac03650. VM has reported a failure when processing extension 'CustomScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=2
[stdout]

[stderr]
ls: cannot access '/does-not-exist': No such file or directory
".
```

I am not able to reproduce your issue.  It isn't clear to me if this is an issue with CustomScript or VMSS.  The fact that you have to uninstall and reinstall is bad.  I am suspicious of CustomScript, but I need a way to prove that CustomScript is doing something wrong.

**Comment by boumenot** [comment] 2018-03-12 17:33
If I run a script that exits with a non-zero code it fails immediately, but that's not what you're describing. I am not sure what's different about what you are doing vs. what I am doing. 

The following is my test example. The command waits six minutes, and then executes a command that will fail.  I tried to simulate a longer running script, by delaying the *bad* command for six minutes.

```json
{
    "commandToExecute": "sleep 360 && ls /does-not-exist"
}
```

The command failed in a little over six minutes, and I was able to issue another command immediately thereafter.

Output:

```text
Deployment failed. Correlation ID: 681e769a-16b3-4315-9374-a8e29ac03650. VM has reported a failure when processing extension 'CustomScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=2
[stdout]

[stderr]
ls: cannot access '/does-not-exist': No such file or directory
".
```

I am not able to reproduce your issue.  It isn't clear to me if this is an issue with CustomScript or VMSS.  The fact that you have to uninstall and reinstall is bad.  I am suspicious of CustomScript, but I need a way to prove that CustomScript is doing something wrong.

**Comment by alexandreweiss** [comment] 2018-03-13 10:26
If the last Custom Extension Script exit is >0, then the VMSS status is reported as Failed. When i deploy the same template, even sending a new parameter to the extension to make it run, the template exits directly because the VMSS state is in the bad status of "Failed". Only the previous extension status is reported.
In your case, you seem to say that even if the extension exit with RC = 2, you are able to deploy the template again and the command in the extension will be played again ? Am I correct ? In such case for me, i need to remove extension first to have the VMSS state reported as "Succeeded" instead of "failed."

**Comment by boumenot** [comment] 2018-03-13 15:49
You are correct.

**Comment by alexandreweiss** [comment] 2018-03-15 15:55
Ok so what can we do when the VMSS is in Failed state and the extension cannot be played again ?

**Comment by boumenot** [comment] 2018-03-15 16:21
I don't know enough about VMSS to give you an intelligent answer.  The VMSS team will need to answer why these are treated different.  I don't believe the VMSS team has an external presence for issues, so I recommend following up with them internally.  If you can get resolution, I am happy to update this thread with any findings.

**Comment by alexandreweiss** [comment] 2018-03-15 16:22
I made a test with a VM instead of a VMSS.
Extension exits with en error code 2 but the VM is still not showing as failed : 
[
        {
                "version": 1,
                "timestampUTC": "2018-03-15T15:53:08Z",
                "status": {
                        "operation": "Enable",
                        "status": "error",
                        "formattedMessage": {
                                "lang": "en",
                                "message": "Enable failed: failed to execute command: command terminated with exit status=2

I tried to run my script without uninstalling the extension and it runs a second time successfully so you are true for VM !

I will try to get in touch with VMSS team internally and update this thread.

Thanks anyway for your time Chris !

**Comment by alexandreweiss** [comment] 2018-03-18 22:32
Just talk to VMSS team. My mistake ! I was running the extension as a top level resource of my template , depending on (using "Depends on" property) the VMSS which was in "Failed" state so execution could never happen.
I moved extension to be part of the extensionProfile of the VMSS and now it works as a charm. I am able to trigger the extension many times even if last exit RC is >0.
Thanks again !
