### ISSUE TITLE
RHEL diagnostic logs going to Table Storage are missing appname and PID.  

### ISSUE THREAD

**Issue by AaronHofer** [Azure/azure-linux-extensions#379] opened 2017-05-04 19:39 UTC
Diagnostic logging to Table Storage is missing the application name and PID in the 'Msg' field.  I'm using the Azure Storage API with C# to query and forward events to our SIEM but the messages aren't complete. 

Here is what rsyslog will log to disk:
May  4 13:41:16 TestLinux123 sshd[12164]: Failed password for root from 1.2.3.4 port 15435 ssh2

Rsyslog correctly logs the app and PID ("sshd[12164]"), but those details are strangely not being recorded in Table Storage.  Without the App name and to a lesser extent the PID, our SIEM can't parse events properly.  I could re-invent the wheel and manually re-add the app names after a lot of research, but I still won't have the PID and it seems like an easy fix to include both the App and PID in the Msg field in table storage. 

Please fix, thanks!

**Comment by hosungsmsft** [comment] 2017-05-04 20:53
Thanks for reporting this issue, but unfortunately, I have to tell you that this behavior is by design currently with LAD 2.3. We are also very near the release of LAD 3.0, which addresses this issue, so please try LAD 3.0 once it becomes available (by EOW next week). Please note that LAD 3.0 is not backward compatible with LAD 2.3, so you'll need to uninstall LAD 2.3 and fresh-install LAD 3.0 for the functionality. Also note that the syslog table name might be different (LinuxsyslogVer2v0 vs LinuxSyslogVer2v0).

Closing this issue in the anticipation of LAD 3.0. Please reactivate this if the issue still persists even after you upgrade to LAD 3.0 next week. Thanks.

**Closed by hosungsmsft** 2017-05-04 20:53 UTC
