### ISSUE TITLE
[OmsAgent] Bad page state in process omicli

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-linux-extensions#933] opened 2019-10-29 02:22 UTC
I know there is a known [kernel bug](https://bugs.centos.org/view.php?id=15181) but since version **1.12.5** of the **OmsAgentForLinux** extension has been released, there are a lot of occurences of this bug.

Other processes are hitting the bug, but it seems it always start with **omicli**:
  
```
Oct 26 03:19:45 azurevm01 kernel: BUG: Bad page state in process omicli  pfn:4d77ff
Oct 26 03:20:07 azurevm01 kernel: BUG: Bad page state in process sh  pfn:3a84b5
Oct 26 03:20:07 azurevm01 kernel: BUG: Bad page state in process sh  pfn:3a84b5
Oct 26 03:20:08 azurevm01 kernel: BUG: Bad page state in process sh  pfn:3a84b5
Oct 26 03:20:08 azurevm01 kernel: BUG: Bad page state in process sh  pfn:3a84b5
```

I could see the issue on RHEL 7 with different kernels:

- 3.10.0-862.2.3.el7.x86_64
- 3.10.0-862.14.4.el7.x86_64
- 3.10.0-957.21.3.el7.x86_64
- 3.10.0-957.27.2.el7.x86_64
- 3.10.0-1062.1.2.el7.x86_64
- 3.10.0-1062.4.1.el7.x86_64

Will follow up internally.

**Comment by johanburati** [comment] 2019-10-29 02:23
Refer to  https://github.com/microsoft/OMS-Agent-for-Linux/issues/1081

**Comment by hestolz** [comment] 2019-10-29 20:04
Johan please open the issue in [this repo](https://github.com/microsoft/omi/issues); omicli is a subcomponent of oms and this issue must be looked at by the appropriate team. Thanks.

**Comment by johanburati** [comment] 2019-10-30 00:09
Ok, I have opened this issue: https://github.com/microsoft/omi/issues/650

**Comment by johanburati** [comment] 2019-10-30 01:10
@hestolz  
That would be good if you could leave this ticket open for a while because this is a ongoing issue, a lot of people are affected by this and some of them will be looking for solution on github.
An open issue is easier to find than a closed one and it's easy to get lost between those three repos: OMS-Agent-for-Linux , azure-linux-extensions and omi

**Comment by eehret** [comment] 2019-11-06 15:29
Double-plus-confirmed.  This is happening to us too.  Fortunately I've only seen the problem on our development servers so far, but I am concerned that this will start happening to Production servers eventually.

**Comment by johanburati** [comment] 2019-11-08 06:50
@eehret Please refer to https://github.com/microsoft/omi/issues/650#issuecomment-550112634

**Comment by eehret** [comment] 2019-11-12 15:23
@johanburati Thanks, your fix there does work for me.  I do hope that Microsoft will fix this properly though.

**Comment by hestolz** [comment] 2020-01-23 16:51
Hi all, we have released numerous hotfixes since the initial omicli page state error arose. It has been a few months since the relevant hotfix went out (https://github.com/microsoft/OMS-Agent-for-Linux/pull/1095), and we haven't seen any customers affected by the original issue. I'll close this issue now; if there are further developments please reopen.

**Closed by hestolz** 2020-01-23 16:51 UTC
