### ISSUE TITLE
OMIGOD Critical Vuln in OMI: OMSAgent Python script needs to be updated

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Azure/azure-linux-extensions#1425] opened 2021-09-16 08:16 UTC
Hello!

It seems that the omsagent version in the bundle script referenced in the following omsagent python script needs to be updated:

https://github.com/Azure/azure-linux-extensions/blob/master/OmsAgent/omsagent.py#L90

![image](https://user-images.githubusercontent.com/9653181/133576243-36d346c8-7f93-4ace-a592-06333c7bb604.png)

I reported something similar in here (already fixed)

https://github.com/microsoft/OMS-Agent-for-Linux/issues/1360

**Comment by Klaas-** [comment] 2021-09-16 14:58
this is a duplicate of #1419

**Closed** 2021-10-10 06:55 UTC
