### ISSUE TITLE
Data collected by LAD 3.0.107 are not displaying on Portal

### ISSUE THREAD

**Issue by msevastian** [Azure/azure-linux-extensions#417] opened 2017-07-03 16:17 UTC
I have provisioned LAD extension (v. 3.0.107), with public settings defined here https://github.com/Azure/azure-linux-extensions/blob/master/Diagnostic/tests/lad_2_3_compatible_portal_pub_settings.json
Everything seems fine, as I see data in corresponding table
![capture2](https://user-images.githubusercontent.com/28624368/27800862-d9c936fa-6023-11e7-8c3e-c647a7e75ebd.PNG)
But for some reason metrics are not displying on Portal, even after few hours of waiting
![capture](https://user-images.githubusercontent.com/28624368/27800918-2d0795be-6024-11e7-83e6-3c916cad703b.PNG)

**Comment by hosungsmsft** [comment] 2017-07-03 17:02
The only thing that we can suspect is if the resourceId was filled correctly, in case you used the public settings JSON template file. Could you email me your public settings JSON file at hoson@microsoft.com ?

**Comment by msevastian** [comment] 2017-07-03 17:32
Sent you public settings file

**Comment by msevastian** [comment] 2017-07-03 17:37
While reviewing extension log I have noticed that during its installation on VM, also OMS extension is installing, but I haven't added it to VM. Could that somehow be related with this issue?

**Comment by hosungsmsft** [comment] 2017-07-03 17:48
No, the bundled omsagent has nothing to do with this issue. Yes, you are right. LAD 3.0 is now bundled with the omsagent (not the OMS "extension," though).

Thanks also for sending me your public.json file. After looking at this, I found that the issue is your incorrectly supplied resourceId content. I replied by email as well, so I'm closing this issue here. Thanks.

**Closed by hosungsmsft** 2017-07-03 17:48 UTC
