### ISSUE TITLE
'ascii' codec can't encode characters in position 45-110: ordinal not in range(128)

### ISSUE THREAD

**Issue by nikita-rastogi** [Azure/azure-linux-extensions#563] opened 2018-04-17 07:59 UTC
if LAD 3.0.111 throws an error, sometimes that error message is not printed in the logs, as another error is thrown while printing that error message. The error is as follows:
 _'ascii' codec can't encode characters in position 45-110: ordinal not in range(128)_. 

2 machines on which this error was found were in Japan East region. My doubt is that there is somehow a  bad character or a character in Japanese char set created in the error message. And while trying to print that character by using ascii codec, failure happens, as that character is not known to ascii.

**Comment by abhijeetgaiha** [comment] 2018-05-09 16:12
Duplicate of #542.

**Closed by abhijeetgaiha** 2018-05-09 16:12 UTC
Labels: LinuxDiagnostic, bug, to do
