### ISSUE TITLE
LinuxDiagnostic-3.0.111: Problem(s) detected in generated mdsd configuration.

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-linux-extensions#533] opened 2018-03-07 07:53 UTC
I have enabled the diagnostic settings on two new VMs, a Ubuntu 16.04 and Centos 7.3 Marketplace image and I am getting the following error in the log, any suggestion ?

```
2018/03/07 00:25:46 ERROR:CalledProcessError.  Command string was SSL_CERT_FILE=/etc/pki/tls/cert.pem SSL_CERT_DIR=/etc/pki/tls/certs /usr/local/lad/bin/mdsd -v -c /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlC
fg.xml
2018/03/07 00:25:47 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111] Problem(s) detected in generated mdsd configuration. Can't enable, although this install/enable operation is reported as successful so the VM can complete successful startup. Linux Diagnostic Extension will exit. Config validation message: 2018-03-07T00:25:46.8564990Z: Not all GCS env vars are defined. Missing 5: MONITORING_GCS_ENVIRONMENT MONITORING_GCS_ACCOUNT MONITORING_GCS_REGION MONITORING_GC
S_CERT_CERTFILE MONITORING_GCS_CERT_KEYFILE. GCS won't be used.
2018/03/07 00:25:47 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111] Daemon,success,0,Problem(s) detected in generated mdsd configuration. Can't enable, although this install/enable operation is reported as successful so the VM can
complete successful startup. Linux Diagnostic Extension will exit. Config validation message: 2018-03-07T00:25:46.8564990Z: Not all GCS env vars are defined. Missing 5: MONITORING_GCS_ENVIRONMENT MONITORING_GCS_ACCOUNT MONITORING_GCS_REG
ION MONITORING_GCS_CERT_CERTFILE MONITORING_GCS_CERT_KEYFILE. GCS won't be used.
..
2018/03/07 00:25:47 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery>
2018/03/07 00:25:47 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined
2018/03/07 00:25:47 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery>
2018/03/07 00:25:47 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined
2018/03/07 00:25:47 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery>
2018/03/07 00:25:47 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined
2018/03/07 00:25:47 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery>
2018/03/07 00:25:47 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined
2018/03/07 00:25:47 /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery>
```

**Comment by abhijeetgaiha** [comment] 2018-03-07 08:22
Could you provide your LAD config file?

**Comment by benc-uk** [comment] 2018-03-07 15:18
Seeing same problem but also seeing a prob;em with the SAS Token 

```
STATUS MESSAGE Problem(s) detected in generated mdsd configuration. Can't enable, although this install/enable operation is reported as successful so the VM can complete successful startup. Linux Diagnostic Extension will exit. Config validation message: 2018-03-07T15:07:54.5144110Z: Not all GCS env vars are defined. Missing 5: MONITORING_GCS_ENVIRONMENT MONITORING_GCS_ACCOUNT MONITORING_GCS_REGION MONITORING_GCS_CERT_CERTFILE MONITORING_GCS_CERT_KEYFILE. GCS won't be used. Parse reported these messages: /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(3) Error: Invalid SAS token given. Reason: Account SAS has expired ('se' in the past) /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(18) Fatal: AddMonikerEventInfo() failed: No default credential is found. /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(25) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(31) Fatal: AddMonikerEventInfo() failed: No default credential is found. /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(45) Fatal: AddMonikerEventInfo() failed: No default credential is found. /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(60) Fatal: AddMonikerEventInfo() failed: No default credential is found. /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(71) Fatal: AddMonikerEventInfo() failed: No default credential is found. /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(84) Fatal: AddMonikerEventInfo() failed: No default credential is found. /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery> /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery> /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery> /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery> /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery> /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery> /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery> /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery> /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery> /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: No default credentials were defined /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.111/xmlCfg.xml(97) Error: <DerivedEvent> does not define subelement <LADQuery>
```

**Comment by johanburati** [comment] 2018-03-09 05:34
Sent the config file to your MS email.

**Comment by pappavic** [comment] 2018-03-14 06:52
I am also seeing this on Ubuntu 16.04 LTS deployed from Marketplace and Diagnostics enabled through the portal.

**Comment by pawankt** [comment] 2018-04-03 19:14
I had same issue in CentOS 7.0 when sastoken generating command line, manual token from portal working as expected. difference i saw sv=<key> is mid of token string when generating from CLI, also some  / coming in the string. Suspecting that might problem

**Comment by pawankt** [comment] 2018-04-03 19:20
Error: Storage credential validation for table storage failed: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Comment by benc-uk** [comment] 2018-04-03 19:24
Isn't this just supposed to work? Enabling diagnostics from the portal or CLI is a standard admin task and shouldn't require such arcane knowledge of the inner workings of this extension and the WALinuxAgent

**Comment by pawankt** [comment] 2018-04-03 19:36
Retested now, although enabling assume supposed to pull the data, but portal failed with no default credentials exception when sastoken generated from command line. My exception to require CLI knowledge so that we can automate the stuff.

sv=2017-07-29&ss=bt&srt=sco&sp=rwlacu&se=2019-12-31T23:46:10Z&st=2018-04-01T14:46:10Z&spr=https&sig=xxxxx

ss=bt&spr=https&sp=rwlacu&sv=2017-07-29&st=2018-04-01T00%3A00%3A00Z&sig=xxx/M/vxxx/rxxxx%3D&srt=sco&se=2019-12-31T23%3A59%3A59Z

**Comment by pawankt** [comment] 2018-04-03 19:36
where frist one manual creation from portal, another from cli

**Comment by ybping** [comment] 2018-04-13 05:49
I come with same issue from the cli, so is this a bug or not?

**Comment by pawankt** [comment] 2018-04-13 09:14
I was able to manage, try to create sas token from cli instead from gui make sure start time and expire time both provided. Exprire time should not be default 9999-01-01 time

**Comment by pawankt** [comment] 2018-04-13 09:16
Also try to unistall any older version of LAD exists before installing 3x

**Comment by pawankt** [comment] 2018-04-16 14:59
Correct, due that problem i have gave 10yrs down the line.. It was worked

**Comment by abhijeetgaiha** [comment] 2018-05-09 16:11
Duplicate of #577

**Closed by abhijeetgaiha** 2018-05-09 16:11 UTC
Labels: LinuxDiagnostic, to do
